### ISSUE TITLE
Can't clone the submodules within the repository

### ISSUE THREAD

**Issue by NitinMedisetti** [xmos/xcore_sdk#586] opened 2023-03-03 04:58 UTC
git clone --recurse-submodules https://github.com/xmos/xcore_sdk.git

"Cloning into 'C:/Users/{...}/xcore_sdk/modules/core'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:xmos/{......}' into submodule path 'C:/Users/{...}/xcore_sdk/modules/core' failed
Failed to clone 'modules/core'. Retry scheduled"

This showed up for all the submodules.

**Comment by keithm-xmos** [comment] 2023-03-07 20:52
Hi @NitinMedisetti, I apologize that you ran into this issue.   In order to clone all the submodules, you need to have SSH authentication setup on GitHub.com.  See https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by NitinMedisetti** [comment] 2023-03-08 07:47
Hi @keithm-xmos, I've set up SSH authentication with the help of the link you've provided. Even tested it, as shown in https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection
I still can't clone the submodules. It's same as before.

**Comment by keithm-xmos** [comment] 2023-03-08 11:58
Let's try to clone one of the submodules.  Does this command work for you?

```
git clone git@github.com:xmos/lib_xcore_math.git
```

If the above command does work, try these steps to clone the xcore_sdk:

```
git clone git@github.com:xmos/xcore_sdk.git
cd xcore_sdk
git submodule update --init --recursive
```

Please let me know how this goes.  Thanks @keithm-xmos

**Comment by NitinMedisetti** [comment] 2023-03-08 12:21
This is what happened.

![Screenshot 2023-03-08 174731](https://user-images.githubusercontent.com/70515514/223711922-9fe1d527-dbbc-43b9-9bf0-7004d40dff81.png)

This created empty folders for submodels. Just like before.

**Comment by NitinMedisetti** [comment] 2023-03-09 07:27
Oh, my bad. 
Okay, I've added "update". Now I'm back to where I've started.
![image](https://user-images.githubusercontent.com/70515514/223950663-d79458f0-67a5-4f16-85f8-7d1fcd89e208.png)

**Comment by NitinMedisetti** [comment] 2023-03-09 07:29
Now, I've manually downloaded each submodule. But I just wanted to know what caused the issue and how to deal with it.

**Comment by keithm-xmos** [comment] 2023-03-09 12:06
Can you please clarify what commands you ran to download each submodule?  Many of the submodules also contain submodules.  It would be interesting if those work but the xcore_sdk does not.  For example, does this series of commands work for you?

```
git clone git@github.com:xmos/fwk_core.git
cd fwk_core
git submodule update --init --recursive
```

Thanks again!

**Comment by NitinMedisetti** [comment] 2023-03-09 12:21
I didn't use any commands to download submodules. I've manually navigated to each of those submodules in GitHub and downloaded them as zip files.
```
git clone git@github.com:xmos/fwk_core.git
cd fwk_core
git submodule update --init --recursive
```
And these commands didn't work. It's the same as before. 
"Please make sure you have the correct access rights and the repository exists"

**Comment by keithm-xmos** [comment] 2023-03-09 12:27
OK.  Your zip downloads will only work if you walked through each repo and also downloaded its submodules.  If you missed any, you may run into issues trying to build the applications.  

Does this work for you?

```
git clone git@github.com:xmos/lib_xcore_math.git
```

**Comment by NitinMedisetti** [comment] 2023-03-09 13:27
`git clone git@github.com:xmos/lib_xcore_math.git`
Yes this works

And, I made sure I didn't miss any submodules, and the application was built successfully.

**Comment by keithm-xmos** [comment] 2023-03-14 20:00
Closing issue as we are unable to reproduce.

**Closed by keithm-xmos** 2023-03-14 20:00 UTC
Labels: type:bug
